

const data = [
    {
        id: 1,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03/2023',
      },
      {
        id: 2,
        firstname: 'Domoina',
        lastname: 'ravaka',
        email: 'ravaka@gmail.com',
        post: 'enseignant',
        salary: '45000',
        takeon: '12/03/2023',
      },
      {
        id: 3,
        firstname: 'Adolphe',
        lastname: 'jean',
        email: 'jean@gmail.com',
        post: 'drh',
        salary: '2500000',
        takeon: '12/03/2023',
      },
      {
        id: 4,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 5,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 6,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 7,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 8,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 9,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 10,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 11,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      },
      {
        id: 12,
        firstname: 'Ralaikoa',
        lastname: 'Thierry',
        email: 'thierry@gmail.com',
        post: 'developpeur',
        salary: '1500000',
        takeon: '12/03.2023',
      }
]

export default data